#!/bin/sh
if [ "$PWD" = "/home/beet/repo/beets-blog" ]
then
    for i in $(find dist -type f | sed -r 's/dist(.+)$/\1/')
    do 
      node /home/beet/oss/oss-sdk.js $i 'blog'
    done
else
    node /home/beet/oss/oss-sdk.js $1
fi
